// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLhnhhNjXlAZmn6tJ4-rrPsmTdkT-9aKY',
    appId: '1:441451564085:web:4b486ffcf288927f1df57c',
    messagingSenderId: '441451564085',
    projectId: 'e-comerce-749ba',
    authDomain: 'e-comerce-749ba.firebaseapp.com',
    storageBucket: 'e-comerce-749ba.appspot.com',
    measurementId: 'G-7L5RN6CGB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXOLgfO4hEnzf_O6ijxLLzLdv0Buie1zk',
    appId: '1:441451564085:android:9c0486f74c384d4e1df57c',
    messagingSenderId: '441451564085',
    projectId: 'e-comerce-749ba',
    storageBucket: 'e-comerce-749ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh88E2_Sae0GhlEUfXs5mmZDE2B00JG9o',
    appId: '1:441451564085:ios:2e701fea9767b3331df57c',
    messagingSenderId: '441451564085',
    projectId: 'e-comerce-749ba',
    storageBucket: 'e-comerce-749ba.appspot.com',
    iosBundleId: 'com.example.adsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh88E2_Sae0GhlEUfXs5mmZDE2B00JG9o',
    appId: '1:441451564085:ios:45f82a5a589b57aa1df57c',
    messagingSenderId: '441451564085',
    projectId: 'e-comerce-749ba',
    storageBucket: 'e-comerce-749ba.appspot.com',
    iosBundleId: 'com.example.adsApp.RunnerTests',
  );
}
